class Constants:
    EMBEDDING_DIM = 384
    MODEL_NAME = "all-MiniLM-L6-v2"
    DEFAULT_TOP_K = 10
    MAX_BATCH_SIZE = 64
    FAISS_INDEX_FLAT = "Flat"
    FAISS_INDEX_IVF = "IVFFlat"
    SUMMARY_MAX_TOKENS = 150
    SUMMARY_TEMPERATURE = 0.3
    CACHE_TTL = 3600
    MAX_RETRIES = 3
    RETRY_BACKOFF = 2.0
